name: chunkprotector
main: com.craftilandia.chunkprotector.Main
version: 7.0
commands:
    chunk:
        description: Chunk protection.
permissions:
    chunkprotector.unlimited:
        description: To have unlimited chunks claims.
        default: op
